baseURL = "https://cephei8.github.io/"
languageCode = "en-us"
title = "cephei8's site"
author = "cephei8"

[module]
  [[module.imports]]
    path = "github.com/janraasch/hugo-bearblog"

theme = "hugo-bearblog"

[markup.goldmark.renderer]
  unsafe = true

[params]
  hideMadeWithLine = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
